# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('numbers', models.DecimalField(decimal_places=0, max_digits=2)),
                ('favourite', models.BooleanField()),
                ('pungency_degree', models.CharField(choices=[('不辣', '不辣'), ('微辣', '微辣'), ('中辣', '中辣'), ('非常辣', ' 非常辣')], default='不辣', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parkson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parkson.Parkson'),
        ),
    ]
