# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkson', '0002_auto_20170215_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkson',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='PhoneNum'),
        ),
    ]
